# Generated by Django 4.1.6 on 2023-02-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
    ]
