# Generated by Django 4.1.7 on 2023-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
