# Generated by Django 4.1.5 on 2023-01-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimg', models.ImageField(upload_to='pics')),
                ('pname', models.CharField(max_length=250)),
                ('pdetails', models.TextField()),
            ],
        ),
    ]
